# Configuration file for generating images with spritec
#
# Paths in this file are relative to the location of this configuration file

[[spritesheets]]
path = "../../spritesheet0.png"
scale = 2

[[spritesheets.animations]]
frames = { gltf = "gltf/bigboi.gltf", start_time = 0, end_time = 1000, steps = 4 }
frame_width = 64
frame_height = 64
camera = { eye = {x = 0, y = 2.6, z = 8.0}, fov_y = 54 }
outline = { thickness = 0.15 }


[[spritesheets]]
path = "../../spritesheet1.png"
scale = 2

[[spritesheets.animations]]
frames = [
  "obj/bigboi_000001.obj",
  "obj/bigboi_000010.obj",
  "obj/bigboi_000020.obj",
  "obj/bigboi_000030.obj",
]
frame_width = 64
frame_height = 64
camera = { eye = {x = 0, y = 2.6, z = 8.0}, fov_y = 54 }
outline = { thickness = 0.15 }


[[spritesheets]]
path = "../../spritesheet2.png"
scale = 2

[[spritesheets.animations]]
frames = [
  "obj/bigboi_000001.obj",
  "obj/bigboi_000010.obj",
  "obj/bigboi_000020.obj",
  "obj/bigboi_000030.obj",
]
frame_width = 64
frame_height = 64
camera = { eye = {x = 8.0, y = 2.6, z = 0}, fov_y = 54 }


[[spritesheets]]
path = "../../spritesheet3.png"

[[spritesheets.animations]]
frames = [
  "obj/bigboi_000001.obj",
  "obj/bigboi_000010.obj",
  "obj/bigboi_000020.obj",
  "obj/bigboi_000030.obj",
]
frame_width = 64
frame_height = 64
camera = { eye = {x = 0, y = 2.6, z = 8.0}, fov_y = 54 }

[[spritesheets.animations]]
frames = [
  "obj/bigboi_000001.obj",
  "obj/bigboi_000010.obj",
  "obj/bigboi_000020.obj",
  "obj/bigboi_000030.obj",
]
frame_width = 64
frame_height = 64
camera = { eye = {x = 8.0, y = 2.6, z = 0}, fov_y = 54 }


[[poses]]
model = { gltf = "gltf/bigboi.gltf", time = 0 }
path = "../../pose000000.png"
width = 64
height = 64
scale = 2
camera = { eye = {x = 0, y = 2.6, z = 8.0}, fov_y = 54 }

[[poses]]
model = "obj/bigboi_000001.obj"
path = "../../pose000001.png"
width = 64
height = 64
scale = 2
camera = { eye = {x = 0, y = 2.6, z = 8.0}, fov_y = 54 }

[[poses]]
model = "obj/bigboi_000010.obj"
path = "../../pose000002.png"
width = 64
height = 64
scale = 2
camera = { eye = {x = 0, y = 2.6, z = 8.0}, fov_y = 54 }

[[poses]]
model = "obj/bigboi_000020.obj"
path = "../../pose000003.png"
width = 64
height = 64
scale = 2
camera = { eye = {x = 0, y = 2.6, z = 8.0}, fov_y = 54 }

[[poses]]
model = "obj/bigboi_000030.obj"
path = "../../pose000004.png"
width = 64
height = 64
scale = 2
camera = { eye = {x = 0, y = 2.6, z = 8.0}, fov_y = 54 }
